#!/bin/sh

flush=0;
for r in /opt/drupal/util/docker-composer /opt/drupal/web/themes/uvalib-drupal-theme /opt/drupal/web/modules/custom/* /opt/drupal/web/modules/uvaldap
do
   # echo checking $r
   if [ -d $r ]; then	
      cd $r
      git fetch
      changes=`git diff --name-only origin/main| wc -l`
      if [ $changes -gt 0 ]; then
	 echo $changes changes detected.
	 git pull && \
	 flush=1;
      fi
   fi
done

if [ $flush -eq 1 ]; then
	echo "flushing cache...  may take a minute or so..."
	drush cr
fi
